# examples/smoke_test_analysis.py
# -*- coding: utf-8 -*-

"""
Smoke test for analysis modules.

This script tests:

1. analysis/run_further_analysis_proposed.py
2. analysis/error_propagation_analysis.py
3. analysis/train_calibration_baseline.py

It reuses the checkpoint generated by:

    python examples/smoke_test_proposed_framework.py

Expected input:
    results/smoke_test/proposed_framework/basic/checkpoints/single/best.pt

Outputs:
    results/smoke_test/analysis/

Run from project root:

    python examples/smoke_test_analysis.py
"""

from __future__ import annotations

from pathlib import Path
import sys
import json
import shutil
import traceback
from contextlib import redirect_stdout, redirect_stderr

import torch


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))


def load_run_config(exp_dir: Path) -> dict:
    config_path = exp_dir / "run_config.json"
    if not config_path.exists():
        return {}

    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)


def torch_load(path: Path, map_location: str = "cpu"):
    try:
        return torch.load(path, map_location=map_location, weights_only=False)
    except TypeError:
        return torch.load(path, map_location=map_location)


def patch_hier_model_for_further_analysis(further_module, run_config: dict) -> None:
    """
    Patch further.M.Hier3HeadModel so that it uses the same small model structure
    as the proposed-framework smoke-test checkpoint.
    """
    original_cls = further_module.M.Hier3HeadModel

    width = int(run_config.get("width", 32))
    blocks = int(run_config.get("blocks", 4))
    drop2d = float(run_config.get("drop2d", 0.0))
    head_dropout = float(run_config.get("head_dropout", 0.2))
    use_pt_as_feature = bool(run_config.get("use_pt_as_feature", True))

    def smoke_model_factory(*args, **kwargs):
        kwargs["width"] = width
        kwargs["blocks"] = blocks
        kwargs["drop2d"] = drop2d
        kwargs["head_dropout"] = head_dropout
        kwargs["use_pt_as_feature"] = use_pt_as_feature
        return original_cls(*args, **kwargs)

    further_module.M.Hier3HeadModel = smoke_model_factory


def patch_hier_model_for_error_propagation(error_module, run_config: dict) -> None:
    """
    Patch error_propagation_analysis model config so that it matches the
    proposed-framework smoke-test checkpoint.
    """
    error_module.WIDTH = int(run_config.get("width", error_module.WIDTH))
    error_module.BLOCKS = int(run_config.get("blocks", error_module.BLOCKS))
    error_module.DROP2D = float(run_config.get("drop2d", error_module.DROP2D))
    error_module.HEAD_DROPOUT = float(
        run_config.get("head_dropout", error_module.HEAD_DROPOUT)
    )
    error_module.USE_PT_AS_FEATURE = bool(
        run_config.get("use_pt_as_feature", error_module.USE_PT_AS_FEATURE)
    )


def run_further_analysis_test(
    data_root: Path,
    proposed_exp_dir: Path,
    source_ckpt: Path,
    run_config: dict,
    log_path: Path,
) -> tuple[Path, Path]:
    print("\n[1/3] Testing run_further_analysis_proposed.py")

    import analysis.run_further_analysis_proposed as further

    # The current further-analysis script expects stage2_soh/best.pt.
    target_ckpt = proposed_exp_dir / "checkpoints" / "stage2_soh" / "best.pt"
    target_ckpt.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_ckpt, target_ckpt)

    patch_hier_model_for_further_analysis(further, run_config)

    further.EXP_DIR = str(proposed_exp_dir)
    further.DATA_ROOT = str(data_root)
    further.PULSE_LIST = list(map(int, run_config.get("pulse_list", [1000])))
    further.BATCH_SIZE = 512
    further.NUM_WORKERS = 0
    further.SEED = int(run_config.get("seed", 2026))

    with open(log_path, "a", encoding="utf-8") as log_f:
        log_f.write("\n\n" + "=" * 80 + "\n")
        log_f.write("[1/3] run_further_analysis_proposed.py\n")
        log_f.write("=" * 80 + "\n")
        with redirect_stdout(log_f), redirect_stderr(log_f):
            further.main()

    tab_root = proposed_exp_dir / "further_analysis" / "tables"
    test_csv = tab_root / "test_predictions_per_sample.csv"
    train_csv = tab_root / "train_predictions_for_scatter.csv"

    if not test_csv.exists():
        raise RuntimeError(f"Missing further-analysis output: {test_csv}")
    if not train_csv.exists():
        raise RuntimeError(f"Missing further-analysis output: {train_csv}")

    print(f"[OK] further analysis test predictions: {test_csv}")
    print(f"[OK] further analysis train scatter   : {train_csv}")

    return test_csv, train_csv


def run_error_propagation_test(
    data_root: Path,
    proposed_exp_dir: Path,
    source_ckpt: Path,
    run_config: dict,
    analysis_root: Path,
    log_path: Path,
) -> tuple[Path, Path, Path, Path, Path]:
    print("\n[2/3] Testing error_propagation_analysis.py")

    import analysis.error_propagation_analysis as err

    save_dir = analysis_root / "error_propagation"
    save_dir.mkdir(parents=True, exist_ok=True)

    # -------------------------------------------------------------------------
    # Configure the further-analysis module reused by error propagation
    # -------------------------------------------------------------------------
    err.F.EXP_DIR = str(proposed_exp_dir)
    err.F.DATA_ROOT = str(data_root)

    err.F.PULSE_LIST = list(
        map(
            int,
            run_config.get("pulse_list", [1000]),
        )
    )

    err.F.BATCH_SIZE = 512
    err.F.NUM_WORKERS = 0
    err.F.SEED = int(run_config.get("seed", 2026))

    # Small MC settings for smoke test
    err.F.N_MC_SOC = 4
    err.F.N_MC_SOH = 4

    # Error-propagation output directory
    err.SAVE_DIR = str(save_dir)
    err.COUNTERFACTUAL_SEED = int(
        run_config.get("seed", 2026)
    )

    # -------------------------------------------------------------------------
    # Force model loading from the smoke checkpoint
    # -------------------------------------------------------------------------
    ckpt = torch_load(source_ckpt, map_location="cpu")

    if isinstance(ckpt, dict) and "model" in ckpt:
        state_dict = ckpt["model"]
    elif isinstance(ckpt, dict) and "model_state_dict" in ckpt:
        state_dict = ckpt["model_state_dict"]
    elif isinstance(ckpt, dict) and "state_dict" in ckpt:
        state_dict = ckpt["state_dict"]
    else:
        state_dict = ckpt

    stem_key = "encoder.stem.0.weight"

    if stem_key not in state_dict:
        raise RuntimeError(
            f"Cannot infer model width because checkpoint has no key: {stem_key}"
        )

    width = int(state_dict[stem_key].shape[0])

    block_indices = set()

    for key in state_dict.keys():
        if key.startswith("encoder.body."):
            parts = key.split(".")
            if len(parts) >= 3 and parts[2].isdigit():
                block_indices.add(int(parts[2]))

    if not block_indices:
        raise RuntimeError(
            "Cannot infer encoder block count from checkpoint."
        )

    blocks = max(block_indices) + 1

    drop2d = float(run_config.get("drop2d", 0.0))
    head_dropout = float(run_config.get("head_dropout", 0.2))
    use_pt_as_feature = bool(
        run_config.get("use_pt_as_feature", True)
    )

    original_model_cls = err.F.M.Hier3HeadModel

    def smoke_load_model(
        exp_dir,
        num_classes,
        device,
        run_cfg,
    ):
        print(
            "[SMOKE ERROR LOAD MODEL] "
            f"width={width}, blocks={blocks}, "
            f"checkpoint={source_ckpt}"
        )

        model = original_model_cls(
            num_classes=int(num_classes),
            width=width,
            blocks=blocks,
            drop2d=drop2d,
            use_pt_as_feature=use_pt_as_feature,
            head_dropout=head_dropout,
        ).to(device)

        loaded = torch_load(
            source_ckpt,
            map_location=device,
        )

        if isinstance(loaded, dict) and "model" in loaded:
            loaded_state = loaded["model"]
        elif isinstance(loaded, dict) and "model_state_dict" in loaded:
            loaded_state = loaded["model_state_dict"]
        elif isinstance(loaded, dict) and "state_dict" in loaded:
            loaded_state = loaded["state_dict"]
        else:
            loaded_state = loaded

        model.load_state_dict(
            loaded_state,
            strict=True,
        )

        model.eval()
        return model

    err.F.load_model = smoke_load_model

    print(f"[INFO] Error-propagation EXP_DIR = {err.F.EXP_DIR}")
    print(f"[INFO] Error-propagation SAVE_DIR = {err.SAVE_DIR}")
    print(f"[INFO] Error-propagation checkpoint = {source_ckpt}")

    # -------------------------------------------------------------------------
    # Run the actual entry point
    # -------------------------------------------------------------------------
    with open(
        log_path,
        "a",
        encoding="utf-8",
        buffering=1,
    ) as log_f:
        log_f.write("\n\n" + "=" * 80 + "\n")
        log_f.write("[2/3] error_propagation_analysis.py\n")
        log_f.write("=" * 80 + "\n")
        log_f.flush()

        with redirect_stdout(log_f), redirect_stderr(log_f):
            err.main()
            log_f.flush()

    # -------------------------------------------------------------------------
    # Check outputs produced by the current script
    # -------------------------------------------------------------------------
    e0_csv = save_dir / "e0_predictions_per_sample.csv"
    e1_csv = save_dir / "e1_predictions_per_sample.csv"
    e2_csv = save_dir / "e2_predictions_per_sample.csv"
    e3_csv = save_dir / "e3_predictions_per_sample.csv"
    summary_csv = save_dir / "counterfactual_summary.csv"

    expected_outputs = [
        e0_csv,
        e1_csv,
        e2_csv,
        e3_csv,
        summary_csv,
    ]

    for path in expected_outputs:
        if not path.exists():
            raise RuntimeError(
                f"Missing error-propagation output: {path}"
            )

    print(f"[OK] error propagation E0 predictions: {e0_csv}")
    print(f"[OK] error propagation E1 predictions: {e1_csv}")
    print(f"[OK] error propagation E2 predictions: {e2_csv}")
    print(f"[OK] error propagation E3 predictions: {e3_csv}")
    print(f"[OK] error propagation summary       : {summary_csv}")

    return (
        e0_csv,
        e1_csv,
        e2_csv,
        e3_csv,
        summary_csv,
    )


def run_calibration_baseline_test(
    data_root: Path,
    analysis_root: Path,
    log_path: Path,
) -> tuple[Path, Path]:
    print("\n[3/3] Testing train_calibration_baseline.py")

    import analysis.train_calibration_baseline as calib

    exp_dir = analysis_root / "calibration_baseline"

    with open(log_path, "a", encoding="utf-8") as log_f:
        log_f.write("\n\n" + "=" * 80 + "\n")
        log_f.write("[3/3] train_calibration_baseline.py\n")
        log_f.write("=" * 80 + "\n")
        with redirect_stdout(log_f), redirect_stderr(log_f):
            calib.run_experiment(
                data_root=data_root,
                pulse_list=[1000],
                exp_dir=exp_dir,

                width=8,
                blocks=1,
                drop2d=0.0,
                head_dropout=0.1,
                soc_hidden=16,
                soh_hidden=16,

                batch_size=64,
                max_epochs=1,
                early_stopping=False,
                patience=1,
                resume=False,
                num_workers=0,

                seed=2026,
                test_id_frac=0.1,
                test_id_count=0,

                normalize_soc=True,
                zscore_normalize=True,
                normalize_u_with_train_stats=False,
            )

    final_metrics_csv = exp_dir / "metrics" / "final_metrics.csv"
    predictions_csv = exp_dir / "metrics" / "test_predictions.csv"

    if not final_metrics_csv.exists():
        raise RuntimeError(f"Missing calibration output: {final_metrics_csv}")
    if not predictions_csv.exists():
        raise RuntimeError(f"Missing calibration output: {predictions_csv}")

    print(f"[OK] calibration final metrics: {final_metrics_csv}")
    print(f"[OK] calibration predictions  : {predictions_csv}")

    return final_metrics_csv, predictions_csv


def main() -> None:
    data_root = PROJECT_ROOT / "data"

    proposed_exp_dir = (
        PROJECT_ROOT
        / "results"
        / "smoke_test"
        / "proposed_framework"
        / "basic"
    )

    source_ckpt = proposed_exp_dir / "checkpoints" / "single" / "best.pt"

    analysis_root = PROJECT_ROOT / "results" / "smoke_test" / "analysis"
    analysis_root.mkdir(parents=True, exist_ok=True)

    log_path = analysis_root / "analysis_smoke_test.log"

    print("=" * 80)
    print("[ANALYSIS SMOKE TEST]")
    print("=" * 80)
    print(f"[INFO] PROJECT_ROOT     = {PROJECT_ROOT}")
    print(f"[INFO] data_root        = {data_root}")
    print(f"[INFO] proposed_exp_dir = {proposed_exp_dir}")
    print(f"[INFO] source_ckpt      = {source_ckpt}")
    print(f"[INFO] analysis_root    = {analysis_root}")
    print(f"[INFO] log_path         = {log_path}")

    if not data_root.exists():
        raise FileNotFoundError(f"Data folder not found: {data_root}")

    if not source_ckpt.exists():
        raise FileNotFoundError(
            f"Proposed-framework smoke-test checkpoint not found:\n"
            f"{source_ckpt}\n\n"
            f"Please run first:\n"
            f"    python examples/smoke_test_proposed_framework.py"
        )

    run_config = load_run_config(proposed_exp_dir)

    with open(log_path, "w", encoding="utf-8") as log_f:
        log_f.write("=" * 80 + "\n")
        log_f.write("[ANALYSIS SMOKE TEST LOG]\n")
        log_f.write("=" * 80 + "\n")
        log_f.write(f"PROJECT_ROOT: {PROJECT_ROOT}\n")
        log_f.write(f"data_root: {data_root}\n")
        log_f.write(f"proposed_exp_dir: {proposed_exp_dir}\n")
        log_f.write(f"source_ckpt: {source_ckpt}\n")
        log_f.write(f"run_config: {json.dumps(run_config, ensure_ascii=False, indent=2)}\n")

    further_outputs = run_further_analysis_test(
        data_root=data_root,
        proposed_exp_dir=proposed_exp_dir,
        source_ckpt=source_ckpt,
        run_config=run_config,
        log_path=log_path,
    )

    error_outputs = run_error_propagation_test(
        data_root=data_root,
        proposed_exp_dir=proposed_exp_dir,
        source_ckpt=source_ckpt,
        run_config=run_config,
        analysis_root=analysis_root,
        log_path=log_path,
    )

    calibration_outputs = run_calibration_baseline_test(
        data_root=data_root,
        analysis_root=analysis_root,
        log_path=log_path,
    )

    print("\n" + "=" * 80)
    print("[ANALYSIS SMOKE TEST PASSED]")
    print("=" * 80)

    print("\n[Further analysis outputs]")
    for p in further_outputs:
        print(f"[OK] {p}")

    print("\n[Error propagation outputs]")
    for p in error_outputs:
        print(f"[OK] {p}")

    print("\n[Calibration baseline outputs]")
    for p in calibration_outputs:
        print(f"[OK] {p}")

    print(f"\n[SAVED] full log: {log_path}")


if __name__ == "__main__":
    try:
        main()
    except Exception:
        print("\n" + "=" * 80)
        print("[ANALYSIS SMOKE TEST FAILED]")
        print("=" * 80)
        traceback.print_exc()
        sys.exit(1)