# -*- coding: utf-8 -*-
"""
plot_fig5g_material_conditioning.py

Figure 5g:
Soft vs hard material-conditioning ablation.

This script reads the material-conditioning ablation summary generated by
the new ablation code.

Input:
    results/ablation/material_conditioning_ablation/material_conditioning_ablation_summary.csv

Required columns:
    condition, soc_medape_raw, soh_medape_raw

Output:
    results/figures/main/fig5g/fig5g_material_conditioning.png
"""

from __future__ import annotations

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =============================================================================
# Paths
# =============================================================================
INPUT_CSV = (
    "results/ablation/material_conditioning_ablation/"
    "material_conditioning_ablation_summary.csv"
)

SAVE_DIR = "results/figures/main/fig5g"
SAVE_NAME = "fig5g_material_conditioning.png"

os.makedirs(SAVE_DIR, exist_ok=True)


# =============================================================================
# Load data
# =============================================================================
if not os.path.exists(INPUT_CSV):
    raise FileNotFoundError(
        f"Input CSV not found: {INPUT_CSV}\n"
        "Please run the material-conditioning ablation code first."
    )

df = pd.read_csv(INPUT_CSV)

required_cols = [
    "condition",
    "soc_medape_raw",
    "soh_medape_raw",
]

missing = [c for c in required_cols if c not in df.columns]
if missing:
    raise RuntimeError(
        f"Missing required columns in input CSV: {missing}\n"
        f"Available columns: {list(df.columns)}"
    )


# =============================================================================
# Prepare data
# =============================================================================
CONDITION_ORDER = ["Soft", "Hard"]

condition_map = {
    "soft": "Soft",
    "hard": "Hard",
    "material_soft": "Soft",
    "material_hard": "Hard",
}

df = df.copy()
df["condition"] = df["condition"].astype(str).str.strip().str.lower().map(condition_map)

if df["condition"].isna().any():
    bad_values = df.loc[df["condition"].isna(), "condition"].tolist()
    raise RuntimeError(f"Unknown condition names found: {bad_values}")

df = df[df["condition"].isin(CONDITION_ORDER)].copy()

missing_conditions = [c for c in CONDITION_ORDER if c not in set(df["condition"])]
if missing_conditions:
    raise RuntimeError(
        f"Missing required conditions: {missing_conditions}\n"
        "The CSV must contain both Soft and Hard rows."
    )

df["condition"] = pd.Categorical(
    df["condition"],
    categories=CONDITION_ORDER,
    ordered=True,
)
df = df.sort_values("condition").reset_index(drop=True)

plot_df = pd.DataFrame(
    {
        "Method": df["condition"].astype(str),
        "SOC error": df["soc_medape_raw"].astype(float),
        "SOH error": df["soh_medape_raw"].astype(float),
    }
)


# =============================================================================
# Style
# =============================================================================
plt.rcParams.update(
    {
        "font.family": "Arial",
        "font.size": 7,
        "axes.linewidth": 0.7,
        "xtick.major.width": 0.7,
        "ytick.major.width": 0.7,
        "xtick.major.size": 2.5,
        "ytick.major.size": 2.5,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    }
)

COLORS = {
    "Soft": "#5F7F95",
    "Hard": "#B08A78",
}

MARKERS = {
    "Soft": "o",
    "Hard": "s",
}


# =============================================================================
# Plot
# =============================================================================
metrics = ["SOC error", "SOH error"]
y_pos = np.arange(len(metrics))[::-1]

fig_w_cm = 5
fig_h_cm = 4.4

fig, ax = plt.subplots(
    figsize=(fig_w_cm / 2.54, fig_h_cm / 2.54),
    constrained_layout=False,
)

soft_vals = plot_df.loc[
    plot_df["Method"] == "Soft",
    metrics,
].iloc[0].to_numpy(dtype=float)

hard_vals = plot_df.loc[
    plot_df["Method"] == "Hard",
    metrics,
].iloc[0].to_numpy(dtype=float)

for i, y in enumerate(y_pos):
    ax.plot(
        [soft_vals[i], hard_vals[i]],
        [y, y],
        color="#B8B8B8",
        lw=1.4,
        zorder=1,
        solid_capstyle="round",
    )

for method in ["Soft", "Hard"]:
    vals = plot_df.loc[
        plot_df["Method"] == method,
        metrics,
    ].iloc[0].to_numpy(dtype=float)

    ax.scatter(
        vals,
        y_pos,
        s=36,
        color=COLORS[method],
        marker=MARKERS[method],
        edgecolors="none",
        label=method,
        zorder=3,
    )

    for x, y in zip(vals, y_pos):
        ax.text(
            x,
            y + 0.14,
            f"{x:.2f}",
            ha="center",
            va="bottom",
            fontsize=6.5,
            color=COLORS[method],
        )

ax.set_yticks(y_pos)
ax.set_yticklabels(["SOC", "SOH"])

all_vals = np.concatenate([soft_vals, hard_vals])
xmin = np.nanmin(all_vals)
xmax = np.nanmax(all_vals)
pad = max((xmax - xmin) * 0.35, 0.4)

ax.set_xlim(max(0, xmin - pad), xmax + pad)
ax.set_ylim(-0.55, len(metrics) - 0.45)

ax.set_xlabel("Median APE (%)")

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

ax.grid(
    axis="x",
    color="#E6E6E6",
    lw=0.5,
    zorder=0,
)

ax.legend(
    frameon=False,
    loc="upper center",
    bbox_to_anchor=(0.5, 1.25),
    ncol=2,
    handletextpad=0.4,
    columnspacing=1.0,
    fontsize=6.5,
)

plt.subplots_adjust(
    left=0.24,
    right=0.98,
    bottom=0.25,
    top=0.80,
)

save_path = os.path.join(SAVE_DIR, SAVE_NAME)
fig.savefig(save_path, dpi=600, bbox_inches="tight")
plt.close(fig)

print("\n========== Figure 5g data ==========")
print(plot_df.to_string(index=False))
print(f"\n[OK] Saved: {save_path}")