# -*- coding: utf-8 -*-
"""
plot_fig4i_pulse_polarity_effect.py

Figure 4i:
Pulse-polarity complementarity under positive-only, negative-only,
and full bidirectional-pulse settings.

This script reads the output generated by:
    measurement_sensitivity/pulse_polarity_sensitivity.py

Input:
    results/measurement_sensitivity/pulse_polarity/pulse_polarity_sensitivity_summary.csv

Output:
    results/figures/main/fig4i/fig4i_pulse_polarity_effect.png

Note:
    The pulse_polarity_sensitivity.py script only trains and evaluates
    positive-only and negative-only models. The full-pulse result should be
    taken from the full proposed-framework setting and is entered manually here.
"""

from __future__ import annotations

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =============================================================================
# Paths
# =============================================================================
INPUT_CSV = "results/measurement_sensitivity/pulse_polarity/pulse_polarity_sensitivity_summary.csv"
SAVE_DIR = "results/figures/main/fig4i"
SAVE_NAME = "fig4i_pulse_polarity_effect.png"

os.makedirs(SAVE_DIR, exist_ok=True)


# =============================================================================
# Manual full-pulse result
# =============================================================================
FULL_PULSE_RESULT = {
    "Method": "Full pulse",
    "Classification accuracy": 0.923,
    "SOC MedAPE (%)": 4.80,
    "SOH MedAPE (%)": 2.43,
}


# =============================================================================
# Load data
# =============================================================================
if not os.path.exists(INPUT_CSV):
    raise FileNotFoundError(
        f"Input CSV not found: {INPUT_CSV}\n"
        "Please run measurement_sensitivity/pulse_polarity_sensitivity.py first."
    )

df_raw = pd.read_csv(INPUT_CSV)

required_cols = [
    "config",
    "part",
    "test_cls_acc",
    "test_soc_medape_raw",
    "test_soh_medape_raw",
]

missing = [c for c in required_cols if c not in df_raw.columns]
if missing:
    raise RuntimeError(f"Missing required columns in input CSV: {missing}")


def _find_row_by_part(df: pd.DataFrame, part: str) -> pd.Series:
    rows = df[df["part"].astype(str).str.lower() == part.lower()].copy()

    if rows.empty:
        rows = df[df["config"].astype(str).str.lower().str.contains(part.lower())].copy()

    if rows.empty:
        raise RuntimeError(f"No row found for polarity part: {part}")

    return rows.iloc[0]


positive_row = _find_row_by_part(df_raw, "positive")
negative_row = _find_row_by_part(df_raw, "negative")

df = pd.DataFrame(
    [
        {
            "Method": "Positive only",
            "Classification accuracy": float(positive_row["test_cls_acc"]),
            "SOC MedAPE (%)": float(positive_row["test_soc_medape_raw"]),
            "SOH MedAPE (%)": float(positive_row["test_soh_medape_raw"]),
        },
        {
            "Method": "Negative only",
            "Classification accuracy": float(negative_row["test_cls_acc"]),
            "SOC MedAPE (%)": float(negative_row["test_soc_medape_raw"]),
            "SOH MedAPE (%)": float(negative_row["test_soh_medape_raw"]),
        },
        FULL_PULSE_RESULT,
    ]
)

summary_path = os.path.join(SAVE_DIR, "fig4i_pulse_polarity_summary.csv")
df.to_csv(summary_path, index=False, encoding="utf-8-sig")

print("\n[INFO] Loaded metrics:")
print(df)


# =============================================================================
# Helper functions
# =============================================================================
def fmt_value(v: float, metric: str) -> str:
    if metric == "Classification accuracy":
        return f"{v:.3f}"
    return f"{v:.2f}%"


def gain_value(full_v: float, base_v: float, higher_better: bool = True) -> float:
    if not np.isfinite(full_v) or not np.isfinite(base_v) or abs(base_v) < 1e-12:
        return np.nan

    if higher_better:
        return (full_v - base_v) / base_v * 100.0

    return (base_v - full_v) / base_v * 100.0


# =============================================================================
# Plot configuration
# =============================================================================
metrics = [
    "Classification accuracy",
    "SOC MedAPE (%)",
    "SOH MedAPE (%)",
]

titles = [
    "Classification",
    "SOC",
    "SOH",
]

higher_is_better = {
    "Classification accuracy": True,
    "SOC MedAPE (%)": False,
    "SOH MedAPE (%)": False,
}

colors = {
    "Positive only": "#4E79A7",
    "Negative only": "#F28E2B",
    "Full pulse": "#1B9E77",
}

markers = {
    "Positive only": "o",
    "Negative only": "s",
    "Full pulse": "D",
}

plt.rcParams.update(
    {
        "font.family": "Arial",
        "font.size": 8.5,
        "axes.linewidth": 0.85,
        "xtick.major.width": 0.75,
        "ytick.major.width": 0.75,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    }
)


# =============================================================================
# Plot
# =============================================================================
fig, axes = plt.subplots(
    1,
    3,
    figsize=(7 * 5.84 / 5.61, 2.95),
    gridspec_kw={"wspace": 0.42},
)

for ax, metric, title in zip(axes, metrics, titles):
    pos_v = df.loc[df["Method"] == "Positive only", metric].iloc[0]
    neg_v = df.loc[df["Method"] == "Negative only", metric].iloc[0]
    full_v = df.loc[df["Method"] == "Full pulse", metric].iloc[0]

    higher_better = higher_is_better[metric]

    y_single = 0.0
    y_full = 1.0

    vals = np.array([pos_v, neg_v, full_v], dtype=float)
    vals = vals[np.isfinite(vals)]

    vmin = np.min(vals)
    vmax = np.max(vals)

    span = vmax - vmin
    pad = span * 0.42 if span > 0 else max(abs(vmax) * 0.08, 0.05)

    ax.set_xlim(vmin - pad, vmax + pad)
    ax.set_ylim(-0.43, 1.43)

    ax.axhspan(-0.25, 0.25, color="#F2F2F2", alpha=1.0, zorder=0)
    ax.axhspan(0.75, 1.25, color=colors["Full pulse"], alpha=0.075, zorder=0)

    ax.plot(
        [pos_v, neg_v],
        [y_single, y_single],
        color="0.55",
        linewidth=6.0,
        alpha=0.22,
    )

    ax.scatter(
        pos_v,
        y_single,
        s=70,
        color=colors["Positive only"],
        marker=markers["Positive only"],
        edgecolor="white",
        linewidth=0.9,
        zorder=3,
    )

    ax.scatter(
        neg_v,
        y_single,
        s=70,
        color=colors["Negative only"],
        marker=markers["Negative only"],
        edgecolor="white",
        linewidth=0.9,
        zorder=3,
    )

    ax.scatter(
        full_v,
        y_full,
        s=105,
        color=colors["Full pulse"],
        marker=markers["Full pulse"],
        edgecolor="white",
        linewidth=1.0,
        zorder=4,
    )

    arrow_style = dict(arrowstyle="-|>", lw=1.55, alpha=0.80)

    ax.annotate(
        "",
        xy=(full_v, y_full - 0.06),
        xytext=(pos_v, y_single + 0.08),
        arrowprops=dict(**arrow_style, color=colors["Positive only"]),
    )

    ax.annotate(
        "",
        xy=(full_v, y_full - 0.06),
        xytext=(neg_v, y_single + 0.08),
        arrowprops=dict(**arrow_style, color=colors["Negative only"]),
    )

    ax.text(
        pos_v,
        y_single - 0.18,
        fmt_value(pos_v, metric),
        ha="center",
    )

    ax.text(
        neg_v,
        y_single + 0.17,
        fmt_value(neg_v, metric),
        ha="center",
    )

    ax.text(
        full_v,
        y_full + 0.17,
        fmt_value(full_v, metric),
        ha="center",
        fontweight="bold",
    )

    gain_pos = gain_value(full_v, pos_v, higher_better)
    gain_neg = gain_value(full_v, neg_v, higher_better)

    ax.text(
        0.98,
        0.5,
        f"vs Pos {gain_pos:+.1f}%\nvs Neg {gain_neg:+.1f}%",
        transform=ax.transAxes,
        ha="right",
        va="center",
        bbox=dict(facecolor="white", alpha=0.9),
    )

    ax.set_title(title)

    if metric == "Classification accuracy":
        ax.set_xlabel("Accuracy")
    else:
        ax.set_xlabel("MedAPE (%)")

    ax.set_yticks([y_single, y_full])
    ax.set_yticklabels(["Single\npolarity", "Full\npulse"])

    ax.grid(axis="x", linestyle="--", alpha=0.3)

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


# =============================================================================
# Save figure
# =============================================================================
save_path = os.path.join(SAVE_DIR, SAVE_NAME)
fig.savefig(save_path, dpi=600, bbox_inches="tight")
plt.close(fig)

print(f"[OK] Saved figure: {save_path}")
print(f"[OK] Saved summary: {summary_path}")