# -*- coding: utf-8 -*-
"""
plot_fig4h_noise_ocv_effect.py

Figure 4h:
Effect of perturbing OCV baseline under structured Gaussian noise.

This script reads the output generated by:
    measurement_sensitivity/input_quality_sensitivity.py

Input:
    results/measurement_sensitivity/input_quality/noise_sensitivity_summary.csv

Output:
    results/figures/main/fig4h/fig4h_noise_ocv_effect.png
"""

from __future__ import annotations

import os
import pandas as pd
import matplotlib.pyplot as plt


# =============================================================================
# Paths
# =============================================================================
INPUT_CSV = "results/measurement_sensitivity/input_quality/noise_sensitivity_summary.csv"
SAVE_DIR = "results/figures/main/fig4h"
SAVE_NAME = "fig4h_noise_ocv_effect.png"

os.makedirs(SAVE_DIR, exist_ok=True)


# =============================================================================
# Load data
# =============================================================================
if not os.path.exists(INPUT_CSV):
    raise FileNotFoundError(
        f"Input CSV not found: {INPUT_CSV}\n"
        "Please run measurement_sensitivity/input_quality_sensitivity.py first."
    )

df = pd.read_csv(INPUT_CSV)

required_cols = [
    "type",
    "level",
    "noise_mode",
    "cls_acc",
    "soc_medape_raw",
    "soh_medape_raw",
]

missing = [c for c in required_cols if c not in df.columns]
if missing:
    raise RuntimeError(f"Missing required columns in input CSV: {missing}")

df = df[df["type"] == "noise"].copy()

df_all = df[df["noise_mode"].isin(["all_perturbed", "none"])].copy()
df_ocv = df[df["noise_mode"].isin(["ocv_preserved", "none"])].copy()

df_all = df_all.sort_values("level").reset_index(drop=True)
df_ocv = df_ocv.sort_values("level").reset_index(drop=True)

if df_all.empty:
    raise RuntimeError("No rows found for noise_mode == 'all_perturbed' or 'none'.")

if df_ocv.empty:
    raise RuntimeError("No rows found for noise_mode == 'ocv_preserved' or 'none'.")


# =============================================================================
# Plot
# =============================================================================
fig, ax1 = plt.subplots(figsize=(4.0, 3.45), dpi=600)

x_all = df_all["level"].to_numpy(dtype=float)
x_ocv = df_ocv["level"].to_numpy(dtype=float)

color_acc_dark = "#1f77b4"
color_acc_light = "#aec7e8"

color_soc_dark = "#d62728"
color_soc_light = "#ff9896"

color_soh_dark = "#2ca02c"
color_soh_light = "#98df8a"

# Accuracy
ax1.plot(
    x_all,
    df_all["cls_acc"],
    color=color_acc_dark,
    marker="o",
    linewidth=2,
    label="Acc (all perturbed)",
)

ax1.plot(
    x_ocv,
    df_ocv["cls_acc"],
    color=color_acc_light,
    marker="o",
    linestyle="--",
    linewidth=2,
    label="Acc (OCV preserved)",
)

ax1.set_xlabel("Noise level")
ax1.set_ylabel("Classification accuracy")
ax1.set_ylim(0, 1)

# SOC / SOH errors
ax2 = ax1.twinx()

ax2.plot(
    x_all,
    df_all["soc_medape_raw"],
    color=color_soc_dark,
    marker="s",
    linewidth=2,
    label="SOC (all perturbed)",
)

ax2.plot(
    x_ocv,
    df_ocv["soc_medape_raw"],
    color=color_soc_light,
    marker="s",
    linestyle="--",
    linewidth=2,
    label="SOC (OCV preserved)",
)

ax2.plot(
    x_all,
    df_all["soh_medape_raw"],
    color=color_soh_dark,
    marker="^",
    linewidth=2,
    label="SOH (all perturbed)",
)

ax2.plot(
    x_ocv,
    df_ocv["soh_medape_raw"],
    color=color_soh_light,
    marker="^",
    linestyle="--",
    linewidth=2,
    label="SOH (OCV preserved)",
)

ax2.set_ylabel("Median APE (%)")

ax1.set_title("Effect of Perturbing OCV Baseline")

# Legend
lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()

ax1.legend(
    lines1 + lines2,
    labels1 + labels2,
    loc="lower center",
    bbox_to_anchor=(0.5, 1.15),
    ncol=3,
    fontsize=8,
    frameon=False,
)

ax1.grid(alpha=0.3)

ax1.spines["top"].set_visible(False)
ax2.spines["top"].set_visible(False)

fig.tight_layout()

save_path = os.path.join(SAVE_DIR, SAVE_NAME)
fig.savefig(save_path, dpi=600, bbox_inches="tight")
plt.close(fig)

print(f"[OK] Saved: {save_path}")