# -*- coding: utf-8 -*-
"""
plot_fig4d_error_propagation_waterfall.py

Figure 4d:
Counterfactual error-propagation waterfall analysis for SOH MedAPE.

This script reads the output generated by:
    analysis/error_propagation_analysis.py

Input:
    results/analysis/error_propagation/counterfactual_summary.csv

Output:
    results/figures/main/fig4d/fig4d_error_propagation_waterfall.png
"""

from __future__ import annotations

import os
import pandas as pd
import matplotlib.pyplot as plt


# =============================================================================
# Paths
# =============================================================================
INPUT_CSV = "results/analysis/error_propagation/counterfactual_summary.csv"
SAVE_DIR = "results/figures/main/fig4d"
SAVE_NAME = "fig4d_error_propagation_waterfall.png"

os.makedirs(SAVE_DIR, exist_ok=True)


# =============================================================================
# Load data
# =============================================================================
if not os.path.exists(INPUT_CSV):
    raise FileNotFoundError(
        f"Input CSV not found: {INPUT_CSV}\n"
        "Please run analysis/error_propagation_analysis.py first."
    )

df = pd.read_csv(INPUT_CSV)

required_cols = [
    "experiment",
    "metric",
    "mean",
    "std",
    "median",
]

missing = [c for c in required_cols if c not in df.columns]
if missing:
    raise RuntimeError(f"Missing required columns in input CSV: {missing}")


# =============================================================================
# Prepare waterfall values
# =============================================================================
TARGET_METRIC = "soh_median_ape_raw"

metric_df = df[df["metric"] == TARGET_METRIC].copy()

if metric_df.empty:
    raise RuntimeError(f"No rows found for metric: {TARGET_METRIC}")

data = metric_df.set_index("experiment")["median"]

exp_list = ["E0", "E1", "E2", "E3"]
missing_exp = [e for e in exp_list if e not in data.index]

if missing_exp:
    raise RuntimeError(f"Missing required experiments: {missing_exp}")

vals = [float(data.loc[e]) for e in exp_list]

labels = ["E0", "E1-E0", "E2-E1", "E3-E2", "E3"]
deltas = [
    vals[0],
    vals[1] - vals[0],
    vals[2] - vals[1],
    vals[3] - vals[2],
    vals[3],
]
bottoms = [
    0,
    vals[0],
    vals[1],
    vals[2],
    0,
]


# =============================================================================
# Plot configuration
# =============================================================================
plt.rcParams["font.family"] = "Arial"

c_base = "#A67C8E"
c_delta = "#C2A3B0"
c_total = "#5F7D8E"
colors = [c_base, c_delta, c_delta, c_delta, c_total]

axis_color = "#2F3E46"
bar_width = 0.9


# =============================================================================
# Plot
# =============================================================================
fig, ax = plt.subplots(figsize=(9, 6))

bars = ax.bar(
    labels,
    deltas,
    bottom=bottoms,
    color=colors,
    edgecolor="none",
    width=bar_width,
)

for i in range(len(deltas) - 1):
    step_y = bottoms[i] + deltas[i]
    ax.plot(
        [i + 0.45, i + 0.55],
        [step_y, step_y],
        color=axis_color,
        linestyle="--",
        linewidth=1.2,
        alpha=0.6,
    )

ax.set_ylabel("SOH MAPE (%)", fontsize=11, fontweight="bold")

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.spines["left"].set_color("#D1D1D1")
ax.spines["bottom"].set_color("#D1D1D1")

for i, bar in enumerate(bars):
    actual_val = deltas[i]
    y_pos = bottoms[i] + actual_val if actual_val > 0 else bottoms[i]

    if 0 < i < len(deltas) - 1:
        txt = f"{actual_val:+.2f}"
    else:
        txt = f"{actual_val:.2f}"

    ax.text(
        bar.get_x() + bar.get_width() / 2.0,
        y_pos + 0.05,
        txt,
        ha="center",
        va="bottom",
        fontsize=10,
        fontweight="bold",
        color=axis_color,
    )

plt.tight_layout()

save_path = os.path.join(SAVE_DIR, SAVE_NAME)
fig.savefig(save_path, dpi=300)
plt.close(fig)

print(f"[OK] Saved: {save_path}")