# -*- coding: utf-8 -*-
"""
plot_fig4i_pulse_polarity_effect.py

Figure 4i:
Pulse-polarity complementarity under positive-only, negative-only,
and full bidirectional-pulse settings.

This script reads the output generated by:
    measurement_sensitivity/pulse_polarity_sensitivity.py

Positive/negative-only input:
    results/measurement_sensitivity/pulse_polarity/
    pulse_polarity_sensitivity_summary.csv

Full-pulse input:
    results/proposed_framework/further_analysis/tables/
    test_predictions_per_sample.csv

Output:
    results/figures/main/fig4i/
        fig4i_pulse_polarity_effect.png
        fig4i_pulse_polarity_effect_pure.png
        fig4i_pulse_polarity_summary.csv

Metrics:
    Material accuracy
    SOC MedAE (%)
    SOH MedAE (%)
"""

from __future__ import annotations

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =============================================================================
# Paths
# =============================================================================
INPUT_CSV = (
    "results/measurement_sensitivity/"
    "pulse_polarity/"
    "pulse_polarity_sensitivity_summary.csv"
)

FULL_PREDICTION_CSV = (
    "results/proposed_framework/"
    "further_analysis/tables/"
    "test_predictions_per_sample.csv"
)

SAVE_DIR = "results/figures/main/fig4i"

FULL_SAVE_NAME = "fig4i_pulse_polarity_effect.png"
PURE_SAVE_NAME = "fig4i_pulse_polarity_effect_pure.png"

os.makedirs(SAVE_DIR, exist_ok=True)


# =============================================================================
# Helpers
# =============================================================================
def _find_first_existing_column(
    df: pd.DataFrame,
    candidates: list[str],
    metric_name: str,
) -> str:
    for col in candidates:
        if col in df.columns:
            return col

    raise RuntimeError(
        f"No column found for {metric_name}. "
        f"Expected one of: {candidates}\n"
        f"Available columns: {list(df.columns)}"
    )


def _find_row_by_part(
    df: pd.DataFrame,
    part: str,
) -> pd.Series:
    rows = df[
        df["part"]
        .astype(str)
        .str.lower()
        == part.lower()
    ].copy()

    if rows.empty:
        rows = df[
            df["config"]
            .astype(str)
            .str.lower()
            .str.contains(part.lower())
        ].copy()

    if rows.empty:
        raise RuntimeError(
            f"No row found for polarity part: {part}"
        )

    return rows.iloc[0]


def _to_percent_scale(values) -> np.ndarray:
    """Convert 0-1 scale to percentage points when needed."""
    arr = pd.to_numeric(values, errors="coerce").to_numpy(dtype=float)
    finite = arr[np.isfinite(arr)]

    if len(finite) > 0 and np.nanmax(np.abs(finite)) <= 1.5:
        arr = arr * 100.0

    return arr


def _load_full_pulse_result(path: str) -> dict:
    """
    Compute the full-pulse metrics directly from per-sample predictions.

    This avoids reusing the old manually entered MedAPE values after the
    manuscript metric has been changed to MedAE.
    """
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Full-pulse prediction CSV not found: {path}\n"
            "Please generate the proposed-framework per-sample predictions first."
        )

    pred = pd.read_csv(path)

    required = [
        "true_label",
        "pred_label",
        "soc_true",
        "soc_pred",
        "soh_true",
        "soh_pred",
    ]

    missing = [c for c in required if c not in pred.columns]
    if missing:
        raise RuntimeError(
            f"Missing required columns in full-pulse prediction CSV: {missing}"
        )

    true_material = (
        pred["true_label"]
        .astype(str)
        .str.split("_")
        .str[0]
    )

    pred_material = (
        pred["pred_label"]
        .astype(str)
        .str.split("_")
        .str[0]
    )

    material_acc = float(
        np.mean(
            true_material.to_numpy()
            == pred_material.to_numpy()
        )
    )

    soc_true = _to_percent_scale(pred["soc_true"])
    soc_pred = _to_percent_scale(pred["soc_pred"])
    soh_true = _to_percent_scale(pred["soh_true"])
    soh_pred = _to_percent_scale(pred["soh_pred"])

    soc_valid = np.isfinite(soc_true) & np.isfinite(soc_pred)
    soh_valid = np.isfinite(soh_true) & np.isfinite(soh_pred)

    if not np.any(soc_valid):
        raise RuntimeError("No valid SOC predictions found for full pulse.")
    if not np.any(soh_valid):
        raise RuntimeError("No valid SOH predictions found for full pulse.")

    soc_medae = float(
        np.median(
            np.abs(
                soc_pred[soc_valid]
                - soc_true[soc_valid]
            )
        )
    )

    soh_medae = float(
        np.median(
            np.abs(
                soh_pred[soh_valid]
                - soh_true[soh_valid]
            )
        )
    )

    return {
        "Method": "Full pulse",
        "Material accuracy": material_acc,
        "SOC MedAE (%)": soc_medae,
        "SOH MedAE (%)": soh_medae,
    }


# =============================================================================
# Load positive/negative-only summary
# =============================================================================
if not os.path.exists(INPUT_CSV):
    raise FileNotFoundError(
        f"Input CSV not found: {INPUT_CSV}\n"
        "Please run measurement_sensitivity/"
        "pulse_polarity_sensitivity.py first."
    )


df_raw = pd.read_csv(INPUT_CSV)

required_base_cols = [
    "config",
    "part",
]

missing_base = [
    c for c in required_base_cols
    if c not in df_raw.columns
]

if missing_base:
    raise RuntimeError(
        f"Missing required columns in input CSV: {missing_base}"
    )


material_acc_col = _find_first_existing_column(
    df_raw,
    [
        "test_material_acc",
        "material_acc",
    ],
    "material accuracy",
)

soc_medae_col = _find_first_existing_column(
    df_raw,
    [
        "test_soc_medae_raw",
        "soc_medae_raw",
    ],
    "SOC MedAE",
)

soh_medae_col = _find_first_existing_column(
    df_raw,
    [
        "test_soh_medae_raw",
        "soh_medae_raw",
    ],
    "SOH MedAE",
)


positive_row = _find_row_by_part(
    df_raw,
    "positive",
)

negative_row = _find_row_by_part(
    df_raw,
    "negative",
)

full_pulse_result = _load_full_pulse_result(
    FULL_PREDICTION_CSV
)


df = pd.DataFrame(
    [
        {
            "Method": "Positive only",
            "Material accuracy": float(
                positive_row[material_acc_col]
            ),
            "SOC MedAE (%)": float(
                positive_row[soc_medae_col]
            ),
            "SOH MedAE (%)": float(
                positive_row[soh_medae_col]
            ),
        },
        {
            "Method": "Negative only",
            "Material accuracy": float(
                negative_row[material_acc_col]
            ),
            "SOC MedAE (%)": float(
                negative_row[soc_medae_col]
            ),
            "SOH MedAE (%)": float(
                negative_row[soh_medae_col]
            ),
        },
        full_pulse_result,
    ]
)


summary_path = os.path.join(
    SAVE_DIR,
    "fig4i_pulse_polarity_summary.csv",
)

df.to_csv(
    summary_path,
    index=False,
    encoding="utf-8-sig",
)

print("\n[INFO] Loaded metrics:")
print(df)


# =============================================================================
# Helper functions for plotting
# =============================================================================
def fmt_value(
    v: float,
    metric: str,
) -> str:
    if metric == "Material accuracy":
        return f"{v * 100.0:.1f}%"

    return f"{v:.2f}%"


def gain_value(
    full_v: float,
    base_v: float,
    higher_better: bool = True,
) -> float:
    if (
        not np.isfinite(full_v)
        or not np.isfinite(base_v)
        or abs(base_v) < 1e-12
    ):
        return np.nan

    if higher_better:
        return (
            (full_v - base_v)
            / base_v
            * 100.0
        )

    return (
        (base_v - full_v)
        / base_v
        * 100.0
    )


# =============================================================================
# Plot configuration
# =============================================================================
metrics = [
    "Material accuracy",
    "SOC MedAE (%)",
    "SOH MedAE (%)",
]

titles = [
    "Material",
    "SOC",
    "SOH",
]

higher_is_better = {
    "Material accuracy": True,
    "SOC MedAE (%)": False,
    "SOH MedAE (%)": False,
}

colors = {
    "Positive only": "#4E79A7",
    "Negative only": "#F28E2B",
    "Full pulse": "#1B9E77",
}

markers = {
    "Positive only": "o",
    "Negative only": "s",
    "Full pulse": "D",
}


plt.rcParams.update(
    {
        "font.family": "Arial",
        "font.size": 8.5,
        "axes.linewidth": 0.85,
        "xtick.major.width": 0.75,
        "ytick.major.width": 0.75,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    }
)


# =============================================================================
# Plot
# =============================================================================
fig, axes = plt.subplots(
    1,
    3,
    figsize=(7 * 5.84 / 5.61, 2.95),
    gridspec_kw={
        "wspace": 0.42,
    },
)


for ax, metric, title in zip(
    axes,
    metrics,
    titles,
):
    pos_v = df.loc[
        df["Method"] == "Positive only",
        metric,
    ].iloc[0]

    neg_v = df.loc[
        df["Method"] == "Negative only",
        metric,
    ].iloc[0]

    full_v = df.loc[
        df["Method"] == "Full pulse",
        metric,
    ].iloc[0]

    higher_better = higher_is_better[metric]

    y_single = 0.0
    y_full = 1.0

    vals = np.array(
        [
            pos_v,
            neg_v,
            full_v,
        ],
        dtype=float,
    )

    vals = vals[
        np.isfinite(vals)
    ]

    vmin = np.min(vals)
    vmax = np.max(vals)

    span = vmax - vmin

    pad = (
        span * 0.42
        if span > 0
        else max(
            abs(vmax) * 0.08,
            0.05,
        )
    )

    ax.set_xlim(
        vmin - pad,
        vmax + pad,
    )

    ax.set_ylim(
        -0.43,
        1.43,
    )

    # -------------------------------------------------------------------------
    # Background
    # -------------------------------------------------------------------------
    ax.axhspan(
        -0.25,
        0.25,
        color="#F2F2F2",
        alpha=1.0,
        zorder=0,
    )

    ax.axhspan(
        0.75,
        1.25,
        color=colors["Full pulse"],
        alpha=0.075,
        zorder=0,
    )

    # -------------------------------------------------------------------------
    # Dumbbell
    # -------------------------------------------------------------------------
    ax.plot(
        [
            pos_v,
            neg_v,
        ],
        [
            y_single,
            y_single,
        ],
        color="0.55",
        linewidth=6.0,
        alpha=0.22,
    )

    # -------------------------------------------------------------------------
    # Points
    # -------------------------------------------------------------------------
    ax.scatter(
        pos_v,
        y_single,
        s=70,
        color=colors["Positive only"],
        marker=markers["Positive only"],
        edgecolor="white",
        linewidth=0.9,
        zorder=3,
    )

    ax.scatter(
        neg_v,
        y_single,
        s=70,
        color=colors["Negative only"],
        marker=markers["Negative only"],
        edgecolor="white",
        linewidth=0.9,
        zorder=3,
    )

    ax.scatter(
        full_v,
        y_full,
        s=105,
        color=colors["Full pulse"],
        marker=markers["Full pulse"],
        edgecolor="white",
        linewidth=1.0,
        zorder=4,
    )

    # -------------------------------------------------------------------------
    # Arrows
    # -------------------------------------------------------------------------
    arrow_style = {
        "arrowstyle": "-|>",
        "lw": 1.55,
        "alpha": 0.80,
    }

    ax.annotate(
        "",
        xy=(
            full_v,
            y_full - 0.06,
        ),
        xytext=(
            pos_v,
            y_single + 0.08,
        ),
        arrowprops={
            **arrow_style,
            "color": colors["Positive only"],
        },
    )

    ax.annotate(
        "",
        xy=(
            full_v,
            y_full - 0.06,
        ),
        xytext=(
            neg_v,
            y_single + 0.08,
        ),
        arrowprops={
            **arrow_style,
            "color": colors["Negative only"],
        },
    )

    # -------------------------------------------------------------------------
    # Values
    # -------------------------------------------------------------------------
    ax.text(
        pos_v,
        y_single - 0.18,
        fmt_value(
            pos_v,
            metric,
        ),
        ha="center",
    )

    ax.text(
        neg_v,
        y_single + 0.17,
        fmt_value(
            neg_v,
            metric,
        ),
        ha="center",
    )

    ax.text(
        full_v,
        y_full + 0.17,
        fmt_value(
            full_v,
            metric,
        ),
        ha="center",
        fontweight="bold",
    )

    # -------------------------------------------------------------------------
    # Gains
    # -------------------------------------------------------------------------
    gain_pos = gain_value(
        full_v,
        pos_v,
        higher_better,
    )

    gain_neg = gain_value(
        full_v,
        neg_v,
        higher_better,
    )

    ax.text(
        0.98,
        0.5,
        (
            f"vs Pos {gain_pos:+.1f}%\n"
            f"vs Neg {gain_neg:+.1f}%"
        ),
        transform=ax.transAxes,
        ha="right",
        va="center",
        bbox={
            "facecolor": "white",
            "alpha": 0.9,
        },
    )

    # -------------------------------------------------------------------------
    # Axes
    # -------------------------------------------------------------------------
    ax.set_title(title)

    if metric == "Material accuracy":
        ax.set_xlabel("Material accuracy")
    else:
        ax.set_xlabel("MedAE (%)")

    ax.set_yticks(
        [
            y_single,
            y_full,
        ]
    )

    ax.set_yticklabels(
        [
            "Single\npolarity",
            "Full\npulse",
        ]
    )

    ax.grid(
        axis="x",
        linestyle="--",
        alpha=0.3,
    )

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


# =============================================================================
# Save full version
# =============================================================================
full_save_path = os.path.join(
    SAVE_DIR,
    FULL_SAVE_NAME,
)

fig.savefig(
    full_save_path,
    dpi=600,
    bbox_inches="tight",
)


# =============================================================================
# Pure version
# =============================================================================
for ax in axes:
    ax.set_title("")
    ax.set_xlabel("")
    ax.set_ylabel("")

    ax.set_xticks([])
    ax.set_yticks([])

    for txt in ax.texts:
        txt.set_visible(False)

    ax.grid(False)

    for spine in ax.spines.values():
        spine.set_visible(False)


fig.legends.clear()

for txt in fig.texts:
    txt.set_visible(False)


pure_save_path = os.path.join(
    SAVE_DIR,
    PURE_SAVE_NAME,
)

fig.savefig(
    pure_save_path,
    dpi=600,
    bbox_inches="tight",
    transparent=True,
)

plt.close(fig)


# =============================================================================
# Finished
# =============================================================================
print("\n[OK] Saved outputs:")
print(f"[OK] Full figure : {full_save_path}")
print(f"[OK] Pure figure : {pure_save_path}")
print(f"[OK] Summary     : {summary_path}")
