# -*- coding: utf-8 -*-
"""
plot_fig5d_fair_enhanced_benchmark.py

Figure 5d:
Fair vs enhanced benchmark comparison.

Panels:
a) Material-capacity classification accuracy
b) SOC MedAPE
c) SOH MedAPE

This script reads the benchmark summary generated by:
    benchmark/run_all_benchmarks.py

Input:
    results/benchmark/benchmark_comparison_summary.csv

Output:
    results/figures/main/fig5d/fig5d_fair_enhanced_benchmark.png
"""

from __future__ import annotations

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =============================================================================
# Paths
# =============================================================================
INPUT_CSV = "results/benchmark/benchmark_comparison_summary.csv"
SAVE_DIR = "results/figures/main/fig5d"
SAVE_NAME = "fig5d_fair_enhanced_benchmark.png"

os.makedirs(SAVE_DIR, exist_ok=True)


# =============================================================================
# Proposed-framework reference result
# =============================================================================
PROPOSED_RESULT = {
    "method": "Proposed",
    "setting": "Proposed",
    "classification_accuracy": 0.9230,
    "soc_medape": 4.80,
    "soh_medape": 2.43,
}


# =============================================================================
# Helpers
# =============================================================================
def find_first_existing_column(df: pd.DataFrame, candidates: list[str]) -> str:
    for col in candidates:
        if col in df.columns:
            return col
    raise RuntimeError(
        "None of the candidate columns were found: "
        f"{candidates}\n"
        f"Available columns: {list(df.columns)}"
    )


def normalize_method_name(name: str) -> str:
    key = str(name).strip().lower()

    mapping = {
        "xgboost": "XGBoost",
        "xgb": "XGBoost",
        "tabnet": "TabNet",
        "node": "NODE",
        "ft_transformer": "FT-Transformer",
        "ft-transformer": "FT-Transformer",
        "fttransformer": "FT-Transformer",
        "proposed": "Proposed",
    }

    return mapping.get(key, str(name))


def normalize_setting_name(name: str) -> str:
    key = str(name).strip().lower()

    mapping = {
        "fair": "Fair",
        "enhanced": "Enhanced",
        "unfair": "Enhanced",
        "controlled": "Enhanced",
        "proposed": "Proposed",
    }

    return mapping.get(key, str(name))


def add_panel_label(ax, label: str) -> None:
    ax.text(
        -0.14,
        1.08,
        label,
        transform=ax.transAxes,
        fontsize=10,
        fontweight="bold",
        ha="left",
        va="top",
    )


def get_value(df: pd.DataFrame, method: str, setting: str, metric: str) -> float:
    sub = df[
        (df["method"].astype(str) == method)
        & (df["setting"].astype(str) == setting)
    ]

    if len(sub) == 0:
        return np.nan

    return float(sub[metric].values[0])


# =============================================================================
# Load and standardize benchmark summary
# =============================================================================
if not os.path.exists(INPUT_CSV):
    raise FileNotFoundError(
        f"Input CSV not found: {INPUT_CSV}\n"
        "Please run benchmark/run_all_benchmarks.py first, for example:\n"
        "python benchmark/run_all_benchmarks.py --models all --setting both"
    )

raw = pd.read_csv(INPUT_CSV)

method_col = find_first_existing_column(
    raw,
    [
        "model",
        "method",
        "Model",
        "Method",
    ],
)

setting_col = find_first_existing_column(
    raw,
    [
        "setting",
        "Setting",
    ],
)

cls_col = find_first_existing_column(
    raw,
    [
        "cls_acc",
        "test_cls_acc",
        "classification_accuracy",
        "Classification Accuracy",
        "mat_acc",
        "mat_acc_raw",
    ],
)

soc_col = find_first_existing_column(
    raw,
    [
        "soc_medape_raw",
        "test_soc_medape_raw",
        "soc_median_ape",
        "soc_median_ape_raw",
        "SOC MedAPE",
        "soc_medape",
    ],
)

soh_col = find_first_existing_column(
    raw,
    [
        "soh_medape_raw",
        "test_soh_medape_raw",
        "soh_median_ape",
        "soh_median_ape_raw",
        "SOH MedAPE",
        "soh_medape",
    ],
)

df = pd.DataFrame(
    {
        "method": raw[method_col].map(normalize_method_name),
        "setting": raw[setting_col].map(normalize_setting_name),
        "classification_accuracy": raw[cls_col].astype(float),
        "soc_medape": raw[soc_col].astype(float),
        "soh_medape": raw[soh_col].astype(float),
    }
)

# Keep only the benchmark rows needed for Figure 5d.
allowed_methods = [
    "TabNet",
    "XGBoost",
    "NODE",
    "FT-Transformer",
]

df = df[df["method"].isin(allowed_methods)].copy()
df = df[df["setting"].isin(["Fair", "Enhanced"])].copy()

# Add proposed-framework result.
df = pd.concat(
    [
        df,
        pd.DataFrame([PROPOSED_RESULT]),
    ],
    ignore_index=True,
)


# =============================================================================
# Validate data
# =============================================================================
methods = [
    "TabNet",
    "XGBoost",
    "NODE",
    "FT-Transformer",
    "Proposed",
]

required_pairs = []
for method in methods[:-1]:
    required_pairs.append((method, "Fair"))
    required_pairs.append((method, "Enhanced"))
required_pairs.append(("Proposed", "Proposed"))

missing_pairs = []
for method, setting in required_pairs:
    sub = df[(df["method"] == method) & (df["setting"] == setting)]
    if sub.empty:
        missing_pairs.append((method, setting))

if missing_pairs:
    raise RuntimeError(
        "Missing method/setting pairs required for Figure 5d:\n"
        + "\n".join([f"  {m}, {s}" for m, s in missing_pairs])
        + "\n\nPlease make sure benchmark_comparison_summary.csv contains both "
        "fair and enhanced results for all benchmark models."
    )


# =============================================================================
# Plot configuration
# =============================================================================
plt.rcParams.update(
    {
        "font.family": "Arial",
        "font.size": 8,
        "axes.linewidth": 0.8,
        "xtick.major.width": 0.8,
        "ytick.major.width": 0.8,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "savefig.dpi": 600,
    }
)

metrics = [
    ("classification_accuracy", "Classification accuracy", "higher"),
    ("soc_medape", "SOC MedAPE (%)", "lower"),
    ("soh_medape", "SOH MedAPE (%)", "lower"),
]

colors = {
    "Fair": "#BDBBBB",
    "Enhanced": "#4E6E81",
    "Proposed": "#D95F02",
}

edge_color = "#222222"


# =============================================================================
# Plot
# =============================================================================
fig, axes = plt.subplots(1, 3, figsize=(7, 2.35))

x = np.arange(len(methods))
width = 0.35

for ax_idx, (metric, ylabel, direction) in enumerate(metrics):
    ax = axes[ax_idx]

    fair_vals = []
    enhanced_vals = []

    for method in methods:
        if method == "Proposed":
            fair_vals.append(np.nan)
            enhanced_vals.append(np.nan)
        else:
            fair_vals.append(get_value(df, method, "Fair", metric))
            enhanced_vals.append(get_value(df, method, "Enhanced", metric))

    fair_vals = np.asarray(fair_vals, dtype=float)
    enhanced_vals = np.asarray(enhanced_vals, dtype=float)

    proposed_val = get_value(df, "Proposed", "Proposed", metric)

    ax.bar(
        x - width / 2,
        fair_vals,
        width=width,
        color=colors["Fair"],
        edgecolor=edge_color,
        linewidth=0,
        label="Existing models",
        zorder=2,
    )

    ax.bar(
        x + width / 2,
        enhanced_vals,
        width=width,
        color=colors["Enhanced"],
        edgecolor=edge_color,
        linewidth=0,
        label="Existing models + controlled upstream inputs",
        zorder=2,
    )

    ax.bar(
        x[-1],
        proposed_val,
        width=0.42,
        color=colors["Proposed"],
        edgecolor=edge_color,
        linewidth=0,
        label="Proposed",
        zorder=3,
    )

    ax.axhline(
        proposed_val,
        color=colors["Proposed"],
        lw=1.1,
        ls="--",
        alpha=0.8,
        zorder=1,
    )

    add_panel_label(ax, chr(ord("a") + ax_idx))
    ax.set_ylabel(ylabel)

    direction_text = "Lower is better" if direction == "lower" else "Higher is better"

    ax.text(
        0.98,
        0.08,
        direction_text,
        transform=ax.transAxes,
        ha="right",
        va="bottom",
        fontsize=7,
        color="#555555",
    )

    if metric == "classification_accuracy":
        ax.text(
            0.5,
            1.02,
            "No controlled upstream input added",
            transform=ax.transAxes,
            ha="center",
            va="bottom",
            fontsize=7,
            color="#555555",
        )

    ax.set_xticks(x)
    ax.set_xticklabels(methods, rotation=35, ha="right")

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    ax.grid(
        axis="y",
        linestyle="--",
        linewidth=0.45,
        alpha=0.35,
        zorder=0,
    )

    vals = np.concatenate(
        [
            fair_vals[~np.isnan(fair_vals)],
            enhanced_vals[~np.isnan(enhanced_vals)],
            np.array([proposed_val]),
        ]
    )

    ax.set_ylim(0, vals.max() * 1.25)


handles, labels = axes[0].get_legend_handles_labels()
unique = dict(zip(labels, handles))

fig.legend(
    unique.values(),
    unique.keys(),
    loc="upper center",
    bbox_to_anchor=(0.5, 1.08),
    ncol=3,
    frameon=False,
    fontsize=8,
    handlelength=1.2,
    columnspacing=1.1,
)

plt.tight_layout(w_pad=1.25)

save_path = os.path.join(SAVE_DIR, SAVE_NAME)
fig.savefig(save_path, dpi=600, bbox_inches="tight")
plt.close(fig)

print(f"[OK] Saved: {save_path}")