# -*- coding: utf-8 -*-
"""
plot_fig4f_crate_sensitivity_performance.py

Figure 4f:
C-rate sensitivity performance plot.

This script reads the summary generated by:
    measurement_sensitivity/c_rate_sensitivity.py

Default input:
    results/measurement_sensitivity/c_rate/c_rate_sensitivity_summary.csv

Outputs:
    results/figures/main/fig4f/fig4f_crate_sensitivity_performance.png
    results/figures/main/fig4f/fig4f_crate_sensitivity_performance_pure.png
"""

from __future__ import annotations

import argparse
import os
import re

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =============================================================================
# Default configuration
# =============================================================================
DEFAULT_INPUT_CSV = (
    "results/measurement_sensitivity/c_rate/"
    "c_rate_sensitivity_summary.csv"
)

DEFAULT_OUTPUT_DIR = "results/figures/main/fig4f"

CUSTOM_ORDER = [
    "C1",
    "C2",
    "C3",
    "C8",
    "C10",
    "C9",
    "C7",
    "C4",
    "C6",
    "C5",
    "C11",
]

COLOR_ACC = "#005F73"
COLOR_SOH = "#EE9B00"

DPI = 600


# =============================================================================
# Arguments
# =============================================================================
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate Figure 4f C-rate sensitivity performance plot."
        )
    )

    parser.add_argument(
        "--input_csv",
        type=str,
        default=DEFAULT_INPUT_CSV,
        help="Path to c_rate_sensitivity_summary.csv.",
    )

    parser.add_argument(
        "--output_dir",
        type=str,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory to save output figures.",
    )

    parser.add_argument(
        "--dpi",
        type=int,
        default=DPI,
        help="Output resolution.",
    )

    return parser.parse_args()


# =============================================================================
# Data preparation
# =============================================================================
def infer_short_name(config: str) -> str:
    """
    Convert config names such as:
        C1_0p5C
        C10_All

    to:
        C1
        C10
    """
    match = re.match(r"^(C\d+)", str(config))

    if match:
        return match.group(1)

    return str(config)


def normalize_input_summary(df: pd.DataFrame) -> pd.DataFrame:
    """
    Convert c_rate_sensitivity_summary.csv into plotting columns.

    Required output columns:
        short_name
        combo_label
        material_acc
        soh_medae
    """
    df = df.copy()

    required_base = [
        "config",
        "c_rates",
    ]

    missing_base = [
        col
        for col in required_base
        if col not in df.columns
    ]

    if missing_base:
        raise ValueError(
            "Input CSV is missing required columns: "
            f"{missing_base}\n"
            "Please make sure it is generated by "
            "measurement_sensitivity/c_rate_sensitivity.py."
        )

    material_acc_col = None
    for candidate in [
        "test_material_acc",
        "material_acc",
    ]:
        if candidate in df.columns:
            material_acc_col = candidate
            break

    soh_medae_col = None
    for candidate in [
        "test_soh_medae_raw",
        "soh_medae_raw",
    ]:
        if candidate in df.columns:
            soh_medae_col = candidate
            break

    missing_metric_cols = []
    if material_acc_col is None:
        missing_metric_cols.append("test_material_acc")
    if soh_medae_col is None:
        missing_metric_cols.append("test_soh_medae_raw")

    if missing_metric_cols:
        raise ValueError(
            "Input CSV is missing required metric columns: "
            f"{missing_metric_cols}\n"
            "Expected unified metrics for plotting material accuracy "
            "and SOH MedAE."
        )

    df["short_name"] = df["config"].apply(infer_short_name)
    df["combo_label"] = df["c_rates"].astype(str)
    df["material_acc"] = df[material_acc_col].astype(float)
    df["soh_medae"] = df[soh_medae_col].astype(float)

    return df


def prepare_plot_data(input_csv: str) -> pd.DataFrame:
    if not os.path.exists(input_csv):
        raise FileNotFoundError(
            f"Input CSV not found: {input_csv}\n\n"
            "Generate it first by running:\n"
            "    python measurement_sensitivity/"
            "c_rate_sensitivity.py"
        )

    df = pd.read_csv(input_csv)
    df = normalize_input_summary(df)

    available = set(df["short_name"])

    missing_configs = [
        name
        for name in CUSTOM_ORDER
        if name not in available
    ]

    if missing_configs:
        print(
            f"[WARN] Missing configs in input CSV: "
            f"{missing_configs}"
        )

    df = df[
        df["short_name"].isin(CUSTOM_ORDER)
    ].copy()

    df["short_name"] = pd.Categorical(
        df["short_name"],
        categories=CUSTOM_ORDER,
        ordered=True,
    )

    df = (
        df.sort_values("short_name")
        .reset_index(drop=True)
    )

    if df.empty:
        raise RuntimeError(
            "No matching C-rate configurations found "
            "after filtering."
        )

    return df


# =============================================================================
# Full plot
# =============================================================================
def plot_full(
    df: pd.DataFrame,
    output_dir: str,
    dpi: int = DPI,
) -> None:

    os.makedirs(
        output_dir,
        exist_ok=True,
    )

    labels = (
        df["short_name"]
        .astype(str)
        .tolist()
    )

    combo_labels = (
        df["combo_label"]
        .astype(str)
        .tolist()
    )

    material_acc_pct = (
        df["material_acc"]
        .to_numpy(dtype=float)
        * 100.0
    )

    soh_medae = (
        df["soh_medae"]
        .to_numpy(dtype=float)
    )

    tick_labels = [
        f"{short}\n{combo}"
        for short, combo
        in zip(labels, combo_labels)
    ]

    fig, ax_acc = plt.subplots(
        figsize=(12, 6),
        dpi=dpi,
    )

    for spine in [
        "top",
        "right",
        "left",
    ]:
        ax_acc.spines[spine].set_visible(False)

    ax_acc.bar(
        labels,
        material_acc_pct,
        color=COLOR_ACC,
        alpha=0.85,
        width=0.45,
        zorder=3,
    )

    ax_acc.set_ylabel(
        "Material Accuracy (%)",
        fontsize=11,
        fontweight="bold",
        color=COLOR_ACC,
    )

    ax_acc.tick_params(
        axis="y",
        colors=COLOR_ACC,
        labelsize=10,
    )

    ax_acc.set_ylim(
        max(
            0.0,
            float(np.min(material_acc_pct)) - 8.0,
        ),
        108.0,
    )

    ax_soh = ax_acc.twinx()

    for spine in [
        "top",
        "right",
        "left",
        "bottom",
    ]:
        ax_soh.spines[spine].set_visible(False)

    ax_soh.plot(
        labels,
        soh_medae,
        color=COLOR_SOH,
        marker="o",
        linestyle="-",
        linewidth=3,
        markersize=9,
        markerfacecolor="white",
        markeredgewidth=2,
        zorder=4,
    )

    ax_soh.set_ylabel(
        "SOH MedAE (%)",
        fontsize=11,
        fontweight="bold",
        color=COLOR_SOH,
    )

    ax_soh.tick_params(
        axis="y",
        colors=COLOR_SOH,
        labelsize=10,
    )

    ax_soh.set_ylim(
        0,
        float(np.max(soh_medae)) * 1.4,
    )

    for i, value in enumerate(material_acc_pct):
        ax_acc.text(
            i,
            value + 1.0,
            f"{value:.1f}%",
            ha="center",
            fontsize=9,
            fontweight="bold",
            color=COLOR_ACC,
        )

    for i, value in enumerate(soh_medae):
        is_reference = labels[i] == "C10"

        ax_soh.text(
            i,
            value + float(np.max(soh_medae)) * 0.06,
            f"{value:.2f}%",
            ha="center",
            fontsize=9,
            fontweight=(
                "bold"
                if is_reference
                else "normal"
            ),
            color=COLOR_SOH,
        )

    ax_acc.set_xticks(range(len(labels)))
    ax_acc.set_xticklabels(tick_labels, fontsize=9)

    fig.tight_layout()

    save_path = os.path.join(
        output_dir,
        "fig4f_crate_sensitivity_performance.png",
    )

    fig.savefig(
        save_path,
        dpi=dpi,
        bbox_inches="tight",
    )

    plt.close(fig)

    print(f"[OK] Saved: {save_path}")


# =============================================================================
# Pure plot
# =============================================================================
def plot_pure(
    df: pd.DataFrame,
    output_dir: str,
    dpi: int = DPI,
) -> None:

    os.makedirs(
        output_dir,
        exist_ok=True,
    )

    material_acc_pct = (
        df["material_acc"]
        .to_numpy(dtype=float)
        * 100.0
    )

    soh_medae = (
        df["soh_medae"]
        .to_numpy(dtype=float)
    )

    x = np.arange(len(df))

    fig, ax_acc = plt.subplots(
        figsize=(3.5, 4.6),
        dpi=dpi,
    )

    fig.patch.set_alpha(0.0)
    ax_acc.patch.set_alpha(0.0)

    ax_acc.bar(
        x,
        material_acc_pct,
        color=COLOR_ACC,
        alpha=0.9,
        width=0.7,
    )

    ax_acc.set_ylim(
        float(np.min(material_acc_pct)) - 5.0,
        100.0,
    )

    ax_soh = ax_acc.twinx()
    ax_soh.patch.set_alpha(0.0)

    ax_soh.plot(
        x,
        soh_medae,
        color=COLOR_SOH,
        marker="o",
        linewidth=5,
        markersize=12,
        markerfacecolor="white",
        markeredgewidth=3,
    )

    ax_soh.set_ylim(
        0,
        float(np.max(soh_medae)) * 1.2,
    )

    ax_acc.axis("off")
    ax_soh.axis("off")

    save_path = os.path.join(
        output_dir,
        "fig4f_crate_sensitivity_performance_pure.png",
    )

    fig.savefig(
        save_path,
        dpi=dpi,
        transparent=True,
        bbox_inches="tight",
        pad_inches=0,
    )

    plt.close(fig)

    print(f"[OK] Saved: {save_path}")


# =============================================================================
# Main
# =============================================================================
def main() -> None:
    args = parse_args()

    df = prepare_plot_data(args.input_csv)

    plot_full(
        df=df,
        output_dir=args.output_dir,
        dpi=args.dpi,
    )

    plot_pure(
        df=df,
        output_dir=args.output_dir,
        dpi=args.dpi,
    )

    print(
        "[DONE] Figure 4f C-rate sensitivity "
        "performance plots generated."
    )


if __name__ == "__main__":
    main()
